const constants = {
  'SET_STATE'     :'SET_STATE',
  'SELECT_USER'   :'SELECT_USER',
  'ADD_TASK'      :'ADD_TASK',
  'REMOVE_TASK'   :'REMOVE_TASK',
  'ADD_ITEM'      :'ADD_ITEM',
  'REMOVE_ITEM'   :'REMOVE_ITEM',
  'ADD_COMMENT'   :'ADD_COMMENT',
  'REMOVE_COMMENT':'REMOVE_COMMENT',
  'SET_ITEM_COMPLETE': 'SET_ITEM_COMPLETE'
}
export default constants
